name: Build & Deploy Staging Version
on:
  push:
    branches: [ staging ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy The Vlage Staging
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{secrets.SSH_HOST}}
        key: ${{secrets.SSH_KEY}}
        username: ${{secrets.SSH_USERNAME}}
        script: |
          cd /home/backend
          git pull origin staging
          composer install --no-dev
          php artisan migrate --force
          php artisan roles:update
          php artisan cache:clear && php artisan config:clear && php artisan view:clear && php artisan route:clear
          php artisan config:cache && php artisan view:cache && php artisan route:cache
          supervisorctl restart thevlage-worker:
          supervisorctl restart thevlage_horizon:
          systemctl restart nginx
          systemctl reload nginx
          echo 'Deployment Successful!'
